[package]
name = "benchpeek-app"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "benchpeek"
path = "src/main.rs"

[dependencies]
benchpeek-core = { path = "../benchpeek-core" }
benchpeek-plugin = { path = "../benchpeek-plugin" }
benchpeek-wasm-host = { path = "../benchpeek-wasm-host" }
ascii-kv = { path = "../../plugins/ascii-kv" }
can-raw = { path = "../../plugins/can-raw" }
anyhow = "1"
fastrand = "2"
serialport = "4"
eframe = "0.36.1"
egui = "0.36.1"
egui_plot = "0.37.0"
socketcan = { version = "4.0.0", features = ["enumerate"] }
nusb = "0.2.7"

image = { version = "0.25", default-features = false, features = ["jpeg"] }
